// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBIrCzRfV_Es5Ev-VDuXeDIJ2klrolZRs',
    appId: '1:616819595111:web:01006a475d81189d5e01c2',
    messagingSenderId: '616819595111',
    projectId: 'instaclone-86ac6',
    authDomain: 'instaclone-86ac6.firebaseapp.com',
    storageBucket: 'instaclone-86ac6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4FqxIpHkVlT04FRNmW4RM4q0j7K5ZN-A',
    appId: '1:616819595111:android:ffa0f06bf44b1b865e01c2',
    messagingSenderId: '616819595111',
    projectId: 'instaclone-86ac6',
    storageBucket: 'instaclone-86ac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvvE0db1xwDyRrdXgWM22Wu6rU-DZ_SlA',
    appId: '1:616819595111:ios:191404001da37d3b5e01c2',
    messagingSenderId: '616819595111',
    projectId: 'instaclone-86ac6',
    storageBucket: 'instaclone-86ac6.appspot.com',
    iosClientId: '616819595111-3k2qj2n65llhpsb10cg0vsvd984p4ijp.apps.googleusercontent.com',
    iosBundleId: 'com.example.insta',
  );
}
